/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageProducts;

import ManagerPage.Manager;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maria
 */
public class ManageProducts extends javax.swing.JFrame {

    /**
     * Creates new form ManageRequests
     */
    public ManageProducts() {
        initComponents();
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdescriere = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtexpirare = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtpret = new javax.swing.JTextField();
        txtingredient = new javax.swing.JTextField();
        txtprescriptie = new javax.swing.JTextField();
        txtcantitate = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        jLabel1.setText("Manage Products");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 0, 183, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e881bba87734db35285d04ea1ddec35f - Copy.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(27, 30, 135, 150);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nume", "descriere", "expirare", "prescriptie", "ingredient", "pret", "cantitate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 10, 359, 338);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 204, 153))); // NOI18N
        jPanel1.setLayout(null);

        txtname.setText(" ");
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname);
        txtname.setBounds(90, 20, 90, 30);

        jLabel3.setText("Nume");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(16, 30, 70, 14);

        jLabel4.setText("Descriere");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(16, 61, 70, 10);

        txtdescriere.setText(" ");
        jPanel1.add(txtdescriere);
        txtdescriere.setBounds(90, 60, 90, 30);

        jLabel5.setText("Expirare");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(16, 99, 70, 14);

        txtexpirare.setText(" ");
        jPanel1.add(txtexpirare);
        txtexpirare.setBounds(90, 96, 90, 30);

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 280, 51, 23);

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 280, 51, 23);

        jLabel7.setText("Prescriptie");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(16, 137, 70, 14);

        jLabel8.setText("Ingrediente");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(16, 168, 70, 14);

        jLabel9.setText("Pret");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(16, 211, 60, 14);

        jLabel10.setText("Cantitate");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(16, 249, 70, 14);

        txtpret.setText(" ");
        jPanel1.add(txtpret);
        txtpret.setBounds(90, 208, 90, 30);

        txtingredient.setText(" ");
        jPanel1.add(txtingredient);
        txtingredient.setBounds(90, 170, 90, 30);

        txtprescriptie.setText(" ");
        jPanel1.add(txtprescriptie);
        txtprescriptie.setBounds(90, 134, 90, 30);

        txtcantitate.setText(" ");
        jPanel1.add(txtcantitate);
        txtcantitate.setBounds(90, 246, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(180, 30, 230, 330);
        jPanel1.getAccessibleContext().setAccessibleName("Requests");

        jButton2.setText("Done");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 310, 120, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back2.jpg"))); // NOI18N
        jLabel2.setText(" ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1160, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  Connection con1;
         PreparedStatement insertie;
         private void table_update()
         {
             int c;
                 try {
            Class.forName("com.mysql.jdbc.Driver");
            con1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/Credentials","root","M!lkdrink");
            insertie=con1.prepareStatement("select * from produse");
            ResultSet rs=insertie.executeQuery();
          ResultSetMetaData Rss=rs.getMetaData();
          c=Rss.getColumnCount();
          DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
          Df.setRowCount(0);
          while(rs.next())
          {
              Vector v2=new Vector();
              for (int a=1;a<=c;a++)
              {
                  v2.add(rs.getString("id"));
                  v2.add(rs.getString("nume"));
                  v2.add(rs.getString("descriere"));
                  v2.add(rs.getString("expirare"));
                  v2.add(rs.getString("prescriptie"));
                  v2.add(rs.getString("ingredient"));
                  v2.add(rs.getString("pret"));
                  v2.add(rs.getString("cantitate"));
              }
              Df.addRow(v2);
          }
           
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
                
         }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
         int selectedIndex=jTable1.getSelectedRow();
         try {
             int id= Integer.parseInt(Df.getValueAt(selectedIndex,0).toString());
             String nume=txtname.getText();
              String descriere=txtdescriere.getText();
               String expirare=txtexpirare.getText();
                String ingredient=txtingredient.getText();
                 String prescriptie=txtprescriptie.getText();
                   String pret=txtpret.getText();
             String cantitate=txtcantitate.getText();
                  Class.forName("com.mysql.jdbc.Driver");
            con1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/Credentials","root","M!lkdrink");
            insertie=con1.prepareStatement("update produse set nume=?,descriere=?,expirare=?,prescriptie=?,ingredient=?,pret=?,cantitate=? where id=?");
            
  
            insertie.setString(1,nume);
            insertie.setString(2,descriere);
            insertie.setString(3,expirare);
            insertie.setString(4,prescriptie);
            insertie.setString(5,ingredient);
            insertie.setString(6,pret);
             insertie.setString(7,cantitate);
              insertie.setInt(8,id);
            insertie.executeUpdate();
            JOptionPane.showMessageDialog(this,"S-a updatat inregistrarea");
            table_update();
            txtname.setText("");
             txtdescriere.setText("");
              txtexpirare.setText("");
               txtingredient.setText("");
                txtprescriptie.setText("");
                 txtpret.setText("");
                 txtcantitate.setText("");
              txtname.requestFocus();
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String nume=txtname.getText();
        String descriere=txtdescriere.getText();
         String expirare=txtexpirare.getText();
           String prescriptie=txtprescriptie.getText();
        String ingredient=txtingredient.getText();
         String pret=txtpret.getText();
         String cantitate=txtcantitate.getText();
       
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/Credentials","root","M!lkdrink");
            insertie=con1.prepareStatement("insert into produse(nume,descriere,expirare,prescriptie,ingredient,pret,cantitate)values(?,?,?,?,?,?,?)");
              insertie.setString(1,nume);
            insertie.setString(2,descriere);
            insertie.setString(3,expirare);
             insertie.setString(4,prescriptie);
              insertie.setString(5,ingredient);
               insertie.setString(6,pret);
                insertie.setString(7,cantitate);
            insertie.executeUpdate();
          JOptionPane.showMessageDialog(this,"S-a adaugat inregistrarea");
          table_update();
            txtname.setText("");
             txtdescriere.setText("");
              txtexpirare.setText("");
           txtprescriptie.setText("");
          txtingredient.setText("");
          txtpret.setText("");
          txtcantitate.setText("");
           txtname.requestFocus();
          
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
  DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
         int selectedIndex=jTable1.getSelectedRow();
         txtname.setText(Df.getValueAt(selectedIndex,1).toString());
         txtdescriere.setText(Df.getValueAt(selectedIndex,2).toString());
         txtexpirare.setText(Df.getValueAt(selectedIndex,3).toString());
         txtprescriptie.setText(Df.getValueAt(selectedIndex,4).toString());
         txtingredient.setText(Df.getValueAt(selectedIndex,5).toString());
         txtpret.setText(Df.getValueAt(selectedIndex,6).toString());
            txtcantitate.setText(Df.getValueAt(selectedIndex,7).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          Manager m=new Manager();
      this.setVisible(false);
        m.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcantitate;
    private javax.swing.JTextField txtdescriere;
    private javax.swing.JTextField txtexpirare;
    private javax.swing.JTextField txtingredient;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprescriptie;
    private javax.swing.JTextField txtpret;
    // End of variables declaration//GEN-END:variables
}
