/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DeleteItem;

import ManagerPage.Manager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maria
 */
public class DeleteItem extends javax.swing.JFrame {

    /**
     * Creates new form DeleteItem
     */
    public DeleteItem() {
        initComponents();
         table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnume = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdescriere = new javax.swing.JTextField();
        txtexpirare = new javax.swing.JTextField();
        txtprescriptie = new javax.swing.JTextField();
        txtpret = new javax.swing.JTextField();
        txtingredient = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtcantitate = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e881bba87734db35285d04ea1ddec35f - Copy.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e881bba87734db35285d04ea1ddec35f - Copy.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 0, 140, 150);

        jLabel1.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel1.setText("Delete item");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 0, 197, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 204, 153))); // NOI18N
        jPanel1.setLayout(null);

        jLabel2.setText("Nume");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(16, 37, 60, 14);

        jLabel3.setText("Descriere");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(16, 79, 70, 14);

        jLabel4.setText("An expirare");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(16, 122, 70, 14);

        txtnume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeActionPerformed(evt);
            }
        });
        jPanel1.add(txtnume);
        txtnume.setBounds(93, 34, 80, 30);

        jLabel5.setText("Prescriptie");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(16, 160, 70, 14);

        jLabel8.setText("Ingredient");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(16, 198, 70, 14);

        jLabel9.setText("Pret");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(16, 236, 40, 14);

        txtdescriere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescriereActionPerformed(evt);
            }
        });
        jPanel1.add(txtdescriere);
        txtdescriere.setBounds(93, 76, 80, 40);

        txtexpirare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexpirareActionPerformed(evt);
            }
        });
        jPanel1.add(txtexpirare);
        txtexpirare.setBounds(93, 119, 80, 30);

        txtprescriptie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprescriptieActionPerformed(evt);
            }
        });
        jPanel1.add(txtprescriptie);
        txtprescriptie.setBounds(93, 157, 80, 30);

        txtpret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpretActionPerformed(evt);
            }
        });
        jPanel1.add(txtpret);
        txtpret.setBounds(93, 233, 80, 30);

        txtingredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtingredientActionPerformed(evt);
            }
        });
        jPanel1.add(txtingredient);
        txtingredient.setBounds(93, 195, 80, 30);

        jLabel10.setText("Cantitate");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(16, 274, 60, 14);

        txtcantitate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantitateActionPerformed(evt);
            }
        });
        jPanel1.add(txtcantitate);
        txtcantitate.setBounds(93, 271, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(150, 30, 180, 310);
        jPanel1.getAccessibleContext().setAccessibleName("Item");

        jButton3.setText("Sterge");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 240, 120, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nume", "Descriere", "Expirare", "Prescriptie", "Ingredient", "Pret", "Cantitate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(332, 20, 460, 291);

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 280, 120, 23);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back2.jpg"))); // NOI18N
        jLabel11.setText(" ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-10, 0, 1160, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection con1;
        PreparedStatement insertie;
       private void table_update()
        {   int c;
                 try {
            Class.forName("com.mysql.jdbc.Driver");
            con1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/Credentials","root","M!lkdrink");
            insertie=con1.prepareStatement("select * from produse");
            ResultSet rs=insertie.executeQuery();
          ResultSetMetaData Rss=rs.getMetaData();
          c=Rss.getColumnCount();
          DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
          Df.setRowCount(0);
          while(rs.next())
          {
              Vector v2=new Vector();
              for (int a=1;a<=c;a++)
              {
                  v2.add(rs.getString("id"));
                  v2.add(rs.getString("nume"));
                  v2.add(rs.getString("descriere"));
                  v2.add(rs.getString("expirare"));
                  v2.add(rs.getString("prescriptie"));
                  v2.add(rs.getString("ingredient"));
                  v2.add(rs.getString("pret"));
                  v2.add(rs.getString("cantitate"));
              }
              Df.addRow(v2);
          }
           
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DeleteItem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DeleteItem.class.getName()).log(Level.SEVERE, null, ex);
        }
                }
    private void txtnumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
        int selectedIndex=jTable1.getSelectedRow();
        try {
            int id= Integer.parseInt(Df.getValueAt(selectedIndex,0).toString());
            int dialogResult=JOptionPane.showConfirmDialog(null,"Sunteti sigur ca vreti sa stergeti inregistrarea","Avertizare",JOptionPane.YES_NO_OPTION);
            if (dialogResult==JOptionPane.YES_OPTION)
            {

                Class.forName("com.mysql.jdbc.Driver");
                con1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/Credentials","root","M!lkdrink");
                insertie=con1.prepareStatement("delete from produse where id=?");

                insertie.setInt(1,id);
                insertie.executeUpdate();
                JOptionPane.showMessageDialog(this,"S-a sters inregistrarea");
                table_update();
                txtnume.setText("");
                txtdescriere.setText("");
                txtexpirare.setText("");
                txtingredient.setText("");
                txtprescriptie.setText("");
                txtpret.setText("");
                txtcantitate.setText("");
                txtnume.requestFocus();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DeleteItem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DeleteItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtdescriereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescriereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescriereActionPerformed

    private void txtexpirareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexpirareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtexpirareActionPerformed

    private void txtprescriptieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprescriptieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprescriptieActionPerformed

    private void txtpretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpretActionPerformed

    private void txtingredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtingredientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtingredientActionPerformed

    private void txtcantitateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantitateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantitateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
        int selectedIndex=jTable1.getSelectedRow();
        txtnume.setText(Df.getValueAt(selectedIndex,1).toString());
        txtdescriere.setText(Df.getValueAt(selectedIndex,2).toString());
        txtexpirare.setText(Df.getValueAt(selectedIndex,3).toString());
        txtprescriptie.setText(Df.getValueAt(selectedIndex,4).toString());
        txtingredient.setText(Df.getValueAt(selectedIndex,5).toString());
        txtpret.setText(Df.getValueAt(selectedIndex,6).toString());
        txtcantitate.setText(Df.getValueAt(selectedIndex,7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Manager m=new Manager();
      this.setVisible(false);
        m.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcantitate;
    private javax.swing.JTextField txtdescriere;
    private javax.swing.JTextField txtexpirare;
    private javax.swing.JTextField txtingredient;
    private javax.swing.JTextField txtnume;
    private javax.swing.JTextField txtprescriptie;
    private javax.swing.JTextField txtpret;
    // End of variables declaration//GEN-END:variables
}
